---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - i3

# Install packages
- name: install i3 packages
  package:
    name: "{{ i3_packages }}"
    state: "{{ i3_packages_state }}"
  become: yes
  when: ansible_os_family != 'RedHat'
  tags:
    - i3

# Set up configuration directory
- name: create i3 configuration directory
  file:
    dest: "~/{{ i3_conf_dir }}"
    state: directory
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ i3_users }}"
  tags:
    - "i3"
    - "i3_conf"


# Set up pulseaudio group memberships
- name: set up pulseaudio group memberships
  user:
    append: yes
    groups: audio
    user: "{{ item }}"
  become: yes
  with_items: "{{ i3_users }}"
  tags:
    - "i3"
    - "i3_conf"


# Set up configuration file
- name: configure i3
  template:
    src: "{{ i3_conf_template }}"
    dest: "~/{{ i3_conf_dir }}/{{ i3_conf_file }}"
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ i3_users }}"
  tags:
    - "i3"
    - "i3_conf"

# Set up xinitrc
- name: set up xinitrc
  lineinfile:
    dest: "~/.xinitrc"
    state: present
    create: yes
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec i3"
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ i3_users }}"
  tags:
    - "i3"
    - "i3_conf"
