---
- name: set variable overrides
  set_fact:
    _i3_packages: "{{ i3_packages | default(i3_packages_default | sorted_get(overrides)) }}"
  vars:
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"
  tags:
    - always

- name: install packages
  package:
    name: "{{ _i3_packages }}"
    state: "{{ i3_packages_state | default('present') }}"
  tags:
    - install

- name: create configuration directories
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ i3_conf_dir }}"
    - "{{ i3_rofi_conf_dir }}"
  tags:
    - configure

- name: configure i3
  template:
    src: "{{ i3_conf_template }}"
    dest: "{{ i3_conf_dir }}/{{ i3_conf_file }}"
  tags:
    - configure

- name: configure i3 xresource settings
  template:
    src: "{{ i3_xresources_conf_template }}"
    dest: "~/{{ i3_xresources_conf_file }}"
  tags:
    - configure

- name: configure xresources
  lineinfile:
    dest: "~/{{ i3_xresources_file }}"
    state: present
    create: yes
    insertbefore: "^#include"
    regexp: '#include ".*{{ i3_xresources_conf_file }}.*"'
    line: '#include "{{ i3_xresources_conf_file }}"'
  tags:
    - configure

- name: configure rofi launcher
  template:
    src: "{{ i3_rofi_conf_template }}"
    dest: "{{ i3_rofi_conf_dir }}/{{ i3_rofi_conf_file }}"
  tags:
    - configure

- name: set up xinitrc
  lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec i3"
  tags:
    - configure
