---
# Include variable definitions
- name: "include variable overrides"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "vars/{{ ansible_distribution }}.yml"
      - "vars/{{ ansible_os_family }}.yml"
      skip: true
  tags:
    - i3

# Install packages
- name: install i3 packages
  package: >
    name="{{ i3_packages }}"
    state="{{ i3_packages_state }}"
  become: yes
  when: ansible_os_family != 'RedHat'
  tags:
    - i3

# Set up configuration directory
- name: create i3 configuration directory
  file: >
    dest="~{{ item }}/{{ i3_conf_dir }}"
    state=directory
  become: no
  with_items: "{{ i3_users }}"
  tags:
    - "i3"
    - "i3_conf"


# Set up configuration file
- name: configure i3
  template: >
    src="{{ i3_conf_template }}"
    dest="~{{ item }}/{{ i3_conf_dir }}/{{ i3_conf_file }}"
  become: no
  with_items: "{{ i3_users }}"
  tags:
    - "i3"
    - "i3_conf"

# Set up xinitrc
- name: set up xinitrc
  lineinfile: >
    dest="~{{ item }}/.xinitrc"
    state=present
    create=yes
    insertafter=EOF
    regexp="^exec "
    line="exec i3"
  become: no
  with_items: "{{ i3_users }}"
  tags:
    - "i3"
    - "i3_conf"
