---
- name: Set variable overrides
  ansible.builtin.set_fact:
    _i3_packages: "{{ i3_packages | default(i3_packages_default | sorted_get(overrides)) }}"
  vars:
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"
  tags:
    - always

- name: Install packages
  ansible.builtin.package:
    name: "{{ _i3_packages }}"
    state: "{{ i3_packages_state | default('present') }}"
  tags:
    - install

- name: Create configuration directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
  loop:
    - "{{ i3_conf_dir }}"
    - "{{ i3_rofi_conf_dir }}"
  tags:
    - configure

- name: Configure i3
  ansible.builtin.template:
    src: "{{ i3_conf_template }}"
    dest: "{{ i3_conf_dir }}/{{ i3_conf_file }}"
    force: "{{ i3_conf_force }}"
  tags:
    - configure

- name: Configure i3 xresource settings
  ansible.builtin.template:
    src: "{{ i3_xresources_conf_template }}"
    dest: "~/{{ i3_xresources_conf_file }}"
    force: "{{ i3_conf_force }}"
  tags:
    - configure

- name: Configure xresources
  ansible.builtin.lineinfile:
    dest: "~/{{ i3_xresources_file }}"
    state: present
    create: yes
    insertbefore: "^#include"
    regexp: '#include ".*{{ i3_xresources_conf_file }}.*"'
    line: '#include "{{ i3_xresources_conf_file }}"'
  tags:
    - configure

- name: Configure rofi launcher
  ansible.builtin.template:
    src: "{{ i3_rofi_conf_template }}"
    dest: "{{ i3_rofi_conf_dir }}/{{ i3_rofi_conf_file }}"
  tags:
    - configure

- name: Set up xinitrc
  ansible.builtin.lineinfile:
    dest: ~/.xinitrc
    state: present
    create: yes
    insertafter: EOF
    regexp: "^exec .*"
    line: "exec i3"
  tags:
    - configure
