---
- name: Converge

  hosts: all

  become: yes

  pre_tasks:

    - name: update apt package cache
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
      changed_when: false

  roles:

    - role: nephelaiio.i3
