---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: xenial
    image: ubuntu:xenial
  - name: bionic
    image: ubuntu:bionic
  - name: arch
    image: archlinux/base:latest
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
