---
name: Install

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: 'nephelaiio.i3'

jobs:

  local:
    name: Local install
    runs-on: ubuntu-latest
    steps:

      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.i3'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install poetry
        run: pip3 install poetry

      - name: Run local install
        run: bash install.sh

      - name: Test i3 binary
        run: file /usr/bin/i3

      - name: Test i3 configuration
        run: file ~/.config/i3/config
