---
name: keepalive

on:
  schedule:
    - cron: "55 23 * * 4"

jobs:
  keepalive:
    name: Github Actions keepalive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@master
        with:
          commit_message: "CI Keepalive"
          committer_username: "Ted Cook"
          committer_email: "Ted Cook@example.com"
          auto_push: true
